#!/bin/bash

# System Repositories Sync
emaint --auto sync

# System Update
emerge --ask --verbose --update --deep --newuse --changed-deps=y --with-bdeps=y --backtrack=30 @world
emerge --ask @smart-live-rebuild
eclean --deep distfiles
eclean --deep packages

# Application Launcher Refresh
update-desktop-database /usr/share/applications/
update-mime-database /usr/share/mime

# Linux Kernel Update
linux-update
