#!/bin/bash

# System Repositories Sync
emaint --auto sync

# KDE Plasma Package Accept
cd /etc/portage/package.accept_keywords/
FILES=`find . -xtype l`
for FILE in $FILES;
do
    rm -f $FILE
done
cd /etc/portage/package.unmask/
FILES=`find . -xtype l`
for FILE in $FILES;
do
    rm -f $FILE
done

FILES=`find /var/db/repos/kde/Documentation/package.accept_keywords/ -name "*.keywords" -not -name "*-live.keywords" -not -name "*9999*.keywords"`
for FILE in $FILES;
do
    FILENAME=`basename $FILE`
    if [ ! -f $FILENAME ]; then
      ln -s $FILE
    fi
done

# System Update
emerge --ask --verbose --update --deep --newuse --changed-deps=y --with-bdeps=y @world
emerge --ask @smart-live-rebuild
eclean --deep distfiles
eclean --deep packages

# Application Launcher Refresh
update-desktop-database /usr/share/applications/
update-mime-database /usr/share/mime

# Linux Kernel Update
linux-update
