#!/bin/bash

# Get Now Kernel Version
str=`uname -r`
CurrentLinuxVersion=`echo $str | awk -F'[-]' '{print $1}'`
CurrentLinuxMajorVersion=`echo $CurrentLinuxVersion | awk -F'[.]' '{print $1}'`
CurrentLinuxMinorVersion=`echo $CurrentLinuxVersion | awk -F'[.]' '{print $2}'`
CurrentLinuxRevision=`echo $CurrentLinuxVersion | awk -F'[.]' '{print $3}'`

cd /usr/src/linux

# Update Check
NextLinuxMajorVersion=`grep '^VERSION = ' Makefile | sed -e "s/VERSION = //"`
NextLinuxMinorVersion=`grep '^PATCHLEVEL = ' Makefile | sed -e "s/PATCHLEVEL = //"`
NextLinuxRevision=`grep '^SUBLEVEL = ' Makefile | sed -e "s/SUBLEVEL = //"`

# Update Kernel
if [[ ( $(($CurrentLinuxMajorVersion)) -lt $(($NextLinuxMajorVersion)) ) || \
    ($(($CurrentLinuxMajorVersion)) -eq $(($NextLinuxMajorVersion)) && $(($CurrentLinuxMinorVersion)) -lt $(($NextLinuxMinorVersion))) || \
    ($(($CurrentLinuxMajorVersion)) -eq $(($NextLinuxMajorVersion)) && $(($CurrentLinuxMinorVersion)) -eq $(($NextLinuxMinorVersion)) && $(($CurrentLinuxRevision)) -lt $(($NextLinuxRevision))) ]]; then
    make alldefconfig
    make -j `grep cpu.cores /proc/cpuinfo | sort -u | sed 's/[^0-9]//g'`
    make modules_install
    make install
    grub-install --target=x86_64-efi --efi-directory=/boot
    grub-mkconfig -o /boot/grub/grub.cfg
fi
