#!/bin/bash

cd /usr/local/firestorm/
export AUTOBUILD_VARIABLES_FILE=/usr/local/firestorm/fs-build-variables/variables

if ! [ -d ./phoenix-firestorm ]; then
	git clone https://github.com/FirestormViewer/phoenix-firestorm
	cd ./phoenix-firestorm/
else
	cd ./phoenix-firestorm/
	git fetch
	LOCAL_HASH=`git rev-parse HEAD`
	REMOTE_HASH=`git rev-parse origin/master`
	echo $LOCAL_HASH
	echo $REMOTE_HASH
	if [ "$LOCAL_HASH" = "$REMOTE_HASH" ]; then
		exit
	else
		git pull
		git reset --hard origin/master
		git clean -d -f
	fi
fi
CORES=`grep cpu.cores /proc/cpuinfo | sort -u | sed 's/[^0-9]//g'`
JOBS=`bc <<< "scale=0; 10*((1.5*${CORES})+0.5)/10;"`
curl http://download.airanyumi.net/firestorm-viewer/patches/program_backup_place_change.patch | patch -N -u -p1
autobuild installables edit fmodstudio platform=linux64 hash=7fbf32c0ecb2c8019ec48ecadf949993 url=file:///opt/firestorm/fmodstudio-2.02.20-linux64-240070233.tar.bz2
autobuild configure -A 64 -c ReleaseFS_open -- --fmodstudio --no-opensim --avx2 --package --clean --ninja --btype Release --jobs ${JOBS}
if [ ! -e ./build-linux-x86_64/build.ninja ]; then
	exit
fi
autobuild build -A 64 -c ReleaseFS_open -- --no-configure --ninja --jobs ${JOBS}
ls ./build-linux-x86_64/newview/.Firestorm-x86_64-*.touched >/dev/null 2>&1
if [ $? -ne 0 ]; then
	exit
else
	PACKAGE_FILE=`find . -name 'Phoenix*.tar.xz'`
	cp $PACKAGE_FILE ../
fi
